### ISSUE TITLE
[R2019b] -maci64 Flag for macOS

### ISSUE THREAD

**Issue by jkosciessa** [tplobo/MATLAB_launcher#1]
Thanks for these useful scripts. 

On R2019b, I needed to provide the flag ```-maci64``` for the MATLAB call in [matlab.scpt](https://github.com/tplobo/MATLAB_launcher/blob/04d70fa13d4139be056d78298c689133547e5eed/launch_%3Ebin%3Ematlab.scpt) as the executable did not recognize the OS after upgrading to macOS 15.1.1.

The following did the trick for me:

```
-- Run MATLAB in the background and disown job
...
do script "cd " & quoted form of initialFolder & "; nohup " & quoted form of matlabPath & " -maci64 > /dev/null 2>&1 & disown"
...
```

**Comment by tplobo** [comment]
Hey @jkosciessa, thanks for using them, hehehe!

Now, since your implementation is working for you, I don't think we need to go in these details.
But for completeness I will say:
1. my macOS is also 15.1.1
2. I tested my script with both R2019a and R2020a and both work (I don't have R2019b installed)

Your comment is strange to me because the MATLAB executable should automatically identify the computer architecture necessary if you don't specify it. You can see your architecture with the MATLAB command `computer`. As I am using an Intel i7, I get `MACI64`, which is exactly the architecture identified by the executable and the one you are specifying.

Let me know if you have any comments, otherwise, happy coding to you!

**Comment by jkosciessa** [comment]
I am also unsure what went wrong with the automatic system identification, but a similar issue has been raised [here](https://nl.mathworks.com/matlabcentral/answers/101303-why-do-i-receive-the-error-sorry-we-could-not-determine-the-machine-architecture-for-your-when-ru). Strange variability...

**Comment by tplobo** [comment]
> but a similar issue has been raised [here](https://nl.mathworks.com/matlabcentral/answers/101303-why-do-i-receive-the-error-sorry-we-could-not-determine-the-machine-architecture-for-your-when-ru).

Well @jkosciessa, the issue you linked is not a real issue. This is a forum answer created and answered by the [MathWorks Support Team](https://ch.mathworks.com/matlabcentral/profile/authors/4622813) itself to explain what to do when the launcher does not recognize your architecture.


> Strange variability...

Since we have the same OS version and my launchers work, I'd say there is something about your computer that is not allowing the script to recognize the architecture. Are you on an Apple Silicon mac but running an intel-version of MATLAB using [Rosetta](https://support.apple.com/en-il/102527)?
Since Apple Silicons didn't exist back in 2019, your launcher should not include a `maca64` entry in the `ARCH_LIST` variable; so it won't be able to run MATLAB unless you specify an architecture that existed back in 2019: `glnxa64` or `maci64`.
